name = "Autoscalers"
uuid = "69a6282e-b184-404d-a839-cff20abdae59"
authors = ["mtsch <matijacufar@gmail.com>"]
version = "0.1.0"

[deps]
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extensions]
DataFramesExt = "DataFrames"

[compat]
DataFrames = "1"
Measurements = "2"
Tables = "1"
